"""Gate 1 statistical test report — standalone, thesis-ready.
Consolidates: headline pass@1, McNemar significance, bootstrap CI,
seed-variance, and (once generated) standard-benchmark generalization.
Run any time after 07_significance.py / track_seedvar.sh have produced data
— safe to re-run repeatedly as more evidence lands."""

import json
import subprocess
import sys
from pathlib import Path

HE_DIR = Path(__file__).resolve().parent.parent / "data" / "humaneval"
OUT = Path(__file__).resolve().parent.parent / "GATE1_TEST_REPORT.md"


def rate(fn: str) -> tuple[int, int] | None:
    p = HE_DIR / fn
    if not p.exists():
        return None
    rows = [json.loads(l) for l in p.open() if l.strip()]
    ok = sum(1 for r in rows if r.get("passed"))
    return ok, len(rows)


def main() -> None:
    lines = ["# Gate 1 — Statistical Test Report", ""]
    lines.append("*Generated by `gate1/08_gate1_test_report.py` — safe to regenerate.*\n")

    lines.append("## 1. Headline result\n")
    lines.append("| arm | pass@1 | n |")
    lines.append("|---|---|---|")
    for arm, fn in [("baseline (no gate)", "results_baseline.jsonl"),
                    ("gated, judge v1", "results_gated.jsonl"),
                    ("gated, judge v2", "results_gated_v2.jsonl")]:
        r = rate(fn)
        lines.append(f"| {arm} | {f'{r[0]}/{r[1]} = {r[0]/r[1]:.3f}' if r else 'pending'} | {r[1] if r else '-'} |")

    lines.append("\n## 2. Significance (McNemar, paired) + bootstrap 95% CI\n")
    lines.append("```")
    try:
        out = subprocess.run(
            [sys.executable, str(Path(__file__).parent / "07_significance.py")],
            capture_output=True, text=True, timeout=120,
        )
        lines.append(out.stdout.strip() or out.stderr.strip())
    except Exception as e:
        lines.append(f"(could not run: {e})")
    lines.append("```")

    lines.append("\n## 3. Seed variance (baseline vs. judge v1, 3 seeds)\n")
    sv = HE_DIR / "seed_variance_summary.md"
    lines.append(sv.read_text() if sv.exists() else "*(pending — run `scripts/track_seedvar.sh`)*")

    lines.append("\n## 4. Generalization to standard benchmarks (no synthetic degradation)\n")
    gen = HE_DIR / "generalization_summary.md"
    lines.append(gen.read_text() if gen.exists() else
                 "*(pending — run `scripts/track_generalize.sh`: standard HumanEval, MBPP, "
                 "LiveCodeBench with complete specs, baseline vs. gated judge v1)*")

    lines.append("\n## 5. Interpretation notes for the thesis\n")
    lines.append(
        "- Gate 1's judge trained ONLY on SWE-bench-derived data; HumanEval is a held-out "
        "benchmark never touched during training — no task overlap, so the result reflects "
        "generalization of the ask/assume behavior, not memorization.\n"
        "- The paired McNemar test is the statistically correct test here (same 155 tasks, "
        "two conditions), not an independent-proportions test.\n"
        "- Judge v1's over-questioning rate on fully-specified prompts (~59-60%) is a known "
        "risk for the generalization runs in §4 — those prompts are NOT degraded, so a judge "
        "that over-asks there will show the tradeoff directly. Report this honestly regardless "
        "of which way it points."
    )

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
